# Generated by Django 2.2.6 on 2020-03-28 09:37

from django.db import migrations, models
import switch.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=260)),
                ('floor', models.CharField(max_length=260)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(blank=True, default='', max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('ip', models.CharField(max_length=30, unique=True)),
                ('community', models.CharField(default='public', max_length=30)),
                ('version', models.IntegerField(choices=[(1, 'Version 1C'), (2, 'Version 2C'), (3, 'Version 3C')], default=2)),
                ('type', models.IntegerField(choices=[(0, 'Default'), (1, 'H3C'), (2, 'Cisco')], default=0)),
                ('oidValue', models.IntegerField(default=0)),
                ('versionMode', models.CharField(default='', max_length=230)),
                ('model', models.CharField(default='', max_length=30)),
                ('desc', models.CharField(blank=True, default='', max_length=260)),
                ('date', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=switch.models.Position, to='switch.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oidName', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now=True)),
                ('switch', models.ForeignKey(on_delete=switch.models.Switch, to='switch.Switch')),
            ],
        ),
        migrations.CreateModel(
            name='IfDescr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('descr', models.CharField(default='', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('switch', models.ForeignKey(on_delete=switch.models.Switch, to='switch.Switch')),
            ],
        ),
    ]
