# Generated by Django 2.2.6 on 2020-03-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifdescr',
            name='access',
            field=models.IntegerField(choices=[(0, 'Access Switch'), (1, 'Access Computer'), (2, 'Access Other')], default=0),
        ),
    ]
