# Generated by Django 2.2.6 on 2020-03-29 11:44

from django.db import migrations, models
import switch.models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0002_ifdescr_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'H3C'), (2, 'CISCO')], default=0),
        ),
        migrations.CreateModel(
            name='IpMac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=30, unique=True)),
                ('mac', models.CharField(max_length=30)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('ipStatus', models.IntegerField(choices=[(0, 'offLine'), (1, 'onLine')], default=1)),
                ('switch', models.ForeignKey(on_delete=switch.models.Switch, to='switch.Switch')),
            ],
        ),
    ]
