# Generated by Django 2.2.6 on 2020-04-01 12:01

from django.db import migrations, models
import switch.models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0003_auto_20200329_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=30, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('port', models.ForeignKey(on_delete=switch.models.IfDescr, to='switch.IfDescr')),
            ],
        ),
    ]
