# Generated by Django 2.2.6 on 2020-04-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0004_macindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dhcplease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dhcpid', models.CharField(max_length=30)),
                ('clientid', models.CharField(max_length=30)),
                ('hostName', models.CharField(max_length=50)),
                ('scopeid', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
