# Generated by Django 2.2.6 on 2020-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0005_auto_20200409_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcplease',
            name='clientid',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='dhcplease',
            name='hostName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dhcplease',
            name='scopeid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
