# Generated by Django 2.2.6 on 2020-04-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0006_auto_20200409_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dhcplease',
            old_name='hostName',
            new_name='hostname',
        ),
    ]
