# Generated by Django 2.2.6 on 2020-04-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0007_auto_20200409_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcplease',
            name='clientid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
