# Generated by Django 2.2.6 on 2020-04-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0008_auto_20200409_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(default='', max_length=50)),
                ('clientid', models.CharField(default='', max_length=50)),
                ('switchname', models.CharField(default='', max_length=50)),
                ('switchip', models.CharField(default='', max_length=50)),
                ('switchport', models.CharField(default='', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='switch',
            name='type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'H3C7506'), (2, 'CISCO')], default=0),
        ),
    ]
