# Generated by Django 2.2.6 on 2020-04-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0010_auto_20200415_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='getIP',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0),
        ),
        migrations.AddField(
            model_name='switch',
            name='getMac',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0),
        ),
        migrations.AddField(
            model_name='switch',
            name='getPortStatus',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0),
        ),
        migrations.AddField(
            model_name='switch',
            name='getVersionMode',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0),
        ),
        migrations.AddField(
            model_name='switch',
            name='initPort',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0),
        ),
    ]
