# Generated by Django 2.2.6 on 2020-04-24 12:59

from django.db import migrations, models
import switch.models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0011_auto_20200423_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='getIP',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='getMac',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='getPortStatus',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='getVersionMode',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='initPort',
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('name', models.CharField(default='', max_length=50)),
                ('access', models.IntegerField(choices=[(0, 'Access Switch'), (1, 'Access Computer'), (2, 'Access Other')], default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('switch', models.ForeignKey(on_delete=switch.models.Switch, related_name='ports', to='switch.Switch')),
            ],
            options={
                'verbose_name_plural': 'port detail',
            },
        ),
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=30, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('port', models.ForeignKey(on_delete=switch.models.Port, related_name='macs', to='switch.Port')),
            ],
        ),
    ]
