# Generated by Django 2.2.6 on 2020-04-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0012_auto_20200424_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='oidValue',
        ),
        migrations.AddField(
            model_name='switch',
            name='getData',
            field=models.IntegerField(default=0, help_text='1:enable 2:initPort 4:getIpMac 8:getIfDesc, default Value 0'),
        ),
    ]
