# Generated by Django 2.2.6 on 2020-04-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0013_auto_20200426_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'H3C'), (2, 'H3C7506'), (3, 'H3C5560'), (4, 'H3CS3100V2'), (5, 'S2620POE'), (6, 'CISCO')], default=0),
        ),
        migrations.AlterField(
            model_name='switch',
            name='versionMode',
            field=models.CharField(default='version', help_text='if reqire get version,please input version', max_length=230),
        ),
    ]
