# Generated by Django 2.2.6 on 2020-04-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0014_auto_20200427_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'H3C_S3100V2_26TP_SI'), (2, 'H3C'), (3, 'H3C7506'), (4, 'H3C5560'), (5, 'H3CS3100V2'), (6, 'S2620POE'), (7, 'CISCO')], default=0),
        ),
        migrations.AlterField(
            model_name='switch',
            name='versionMode',
            field=models.TextField(default='version', help_text='if reqire get version,please input version', max_length=230),
        ),
    ]
