# Generated by Django 2.2.6 on 2020-04-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0015_auto_20200428_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='model',
        ),
        migrations.AlterField(
            model_name='switch',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=360),
        ),
    ]
