# Generated by Django 2.2.6 on 2020-05-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0019_auto_20200501_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='error',
        ),
        migrations.AlterField(
            model_name='switch',
            name='versionMode',
            field=models.TextField(blank=True, default='', max_length=230),
        ),
    ]
