# Generated by Django 2.2.6 on 2020-05-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0020_auto_20200502_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='onOff',
            field=models.IntegerField(default=0, help_text='1:initPort 2:initPort 4:getIpMac 8:getIfDesc, default Value 0'),
        ),
    ]
