# Generated by Django 2.2.6 on 2020-05-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0022_auto_20200503_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='versionMode',
            new_name='sysDecr',
        ),
        migrations.AlterField(
            model_name='switch',
            name='getData',
            field=models.IntegerField(default=0, help_text='1:enable 2:initPort 4:getMac 8:getIpMac 16:getVersion 32:makeDesc, default Value 0'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='getMacControl',
            field=models.IntegerField(default=0, help_text='1:standsrtGetmac 2:portAccessCheck 0:default Value '),
        ),
    ]
