# Generated by Django 2.2.6 on 2020-05-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0024_userlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='userloginid',
        ),
    ]
