# Generated by Django 2.1.15 on 2020-05-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0026_auto_20200519_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'CISCO6509'), (2, 'H3C_S3100V2_26TP_SI'), (3, 'H3C'), (4, 'H3C7506'), (5, 'H3C5560'), (6, 'H3CS3100V2'), (7, 'S2620POE'), (8, 'CISCO')], default=0),
        ),
    ]
