# Generated by Django 2.1.15 on 2020-05-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0027_auto_20200521_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switch',
            options={'verbose_name_plural': 'SwitchS'},
        ),
    ]
