# Generated by Django 2.1.15 on 2020-05-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0028_auto_20200521_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='ip',
            field=models.GenericIPAddressField(protocol='ipv4', verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='SwitchID'),
        ),
    ]
