# Generated by Django 2.1.15 on 2020-05-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0030_auto_20200521_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='logintime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
